#!/usr/bin/env bash
# Bash script that install nginx and web server

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"

echo "Hello World" | sudo tee /var/www/html/index..html
sudo nginx -t
sudo service nginx restart
sudo service nginx reload
