#!/usr/bin/env bash
# configure web-02 to be identical to web-01

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/medazza permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo sed -i "/server_name _;/a \n\tadd_header X-Served-By \$HOSTNAME;/" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
